// Generated by Ghidra and manually edited to improve readability and to fix misunderstandings

#include <stdio.h>
#include <stdlib.h>

void p(char *param_1)
{
  printf(param_1);
  return;
}

void n(void)
{
  char buffer[520];
  
  fgets(buffer,0x200,stdin);
  p(buffer);

  if (*(int *)0x8049810 == 0x1025544)
  {
    system("/bin/cat /home/user/level5/.pass");
  }
  return;
}

void main(void)
{
  n();
  return;
}
