// Generated by Ghidra and manually edited to improve readability and to fix misunderstandings

#include <stdio.h>
#include <stdlib.h>

void exit(int __status) // 080483d0 <exit@plt>
{
  void (*got_exit()); // 0x8049828
  got_exit(__status);
}

void _exit(int __status) // 08048390 <_exit@plt>: 
{
  void (*got__exit()); // 0x8049838
  got__exit(__status);
}

void o(void)
{
  system("/bin/sh");
  _exit(1);
}

void n(void)
{
  char buffer[0x200]; // 512 bytes
  
  fgets(buffer, 0x200, stdin);
  printf(buffer);

  exit(1);
}

void main(void)
{
  n();
  return;
}
