// Generated by Ghidra and manually edited to improve readability and to fix misunderstandings

#include <stdio.h>
#include <stdlib.h>

void n(void) // 0x08048454
{
  system("/bin/cat /home/user/level7/.pass");
  return;
}

void m(void) // 0x08048468
{
  puts("Nope");
  return;
}

void main(int argc, char *argv[])
{
  char *buffer       = malloc(0x40);
  void (*func_ptr)() = (void (*)())malloc(4); 
  // addresses are 4 bytes long in this i686 architecture

  func_ptr = m;
  
  // buffer   address always = 134520840 (0x0804a008)
  // func_ptr address always = 134520912 (0x0804a050)
  // 134520912 - 134520840 = 72

  strcpy(buffer, argv[1]);

  func_ptr();
  return;
}
